### ISSUE TITLE
Default to snake case in the `Ethers.get_logs/2` overrides and options

### ISSUE THREAD

**Issue by joaop21** [ExWeb3/elixir_ethers#151]
From the `Ethers.get_logs/2` documentation:

```elixir
  """
  ## Overrides and Options

  - `:address`: Indicates event emitter contract address. (nil means all contracts)
  - `:rpc_client`: The RPC Client to use. It should implement ethereum jsonRPC API. default: Ethereumex.HttpClient
  - `:rpc_opts`: Extra options to pass to rpc_client. (Like timeout, Server URL, etc.)
  - `:fromBlock`: Minimum block number of logs to filter.
  - `:toBlock`: Maximum block number of logs to filter.
  """
```

This naming needs to be more consistent. 
In addition, there's a [naming convention](https://hexdocs.pm/elixir/1.17.3/naming-conventions.html#casing) that Elixir projects should follow. 
In this case, it's clear that `fromBlock` and `toBlock` should instead be `from_block` and `to_block`.

This is in the project's documentation, but following the convention here would make it more intuitive for Elixir developers.

For context, I was using this function and getting no logs because I was using snake case instead of camel case. I only found out about this when logging the raw request.

This leads me to think that validating the `overrides` and `options` might not be a bad idea 🤔

**Comment by alisinabh** [comment]
> In this case, it's clear that fromBlock and toBlock should instead be from_block and to_block.

I agree. This actually happened because these options are passed as-is to the RPC implementation (Ethereumex).

> This leads me to think that validating the overrides and options might not be a bad idea.

What I am in debate about is I'm not sure if we should validate that data in this lib or rely on the RPC implementation to validate it.

**Comment by joaop21** [comment]
> This actually happened because these options are passed as-is to the RPC implementation (Ethereumex).

Yes. I think it's good to allow clients to use whatever RPC implementation they want, but `Ethers` is coupled to `Ethereumex,` which I think is not that good.

My suggestion is to use an `Ethereumex` adapter that transforms `Ethers` options into specific `Ethereumex` options.

**Comment by joaop21** [comment]
I don't have much time to improve the [PR](https://github.com/ExWeb3/elixir_ethers/pull/152), but the idea I suggested would be something like that.
