### ISSUE TITLE
Request: Allow an option to skip checksumming the address of a recovered public key

### ISSUE THREAD

**Issue by robrobbins** [ExWeb3/elixir_ethers#99]
there are cases where a user may be working with other addresses that are not in a CS state (from input data for ex) and would want a newly recovered address to be the same. 

I have such a one and as it is i have to `downcase` the recovered addr where I would prefer telling `public_key_to_address` that [checksum: false] or some such. Perhaps since the ..to_checksum method is available we could allow the default to be false and instruct a user to use the method if desired.

**Comment by alisinabh** [comment]
I would argue the best way to compare addresses would be to compare them in a decoded state (binary) but overall I would agree with having an option like `:checksumed` in `public_key_to_address` function.

However I don't think having it set to false by default would be a good idea.
